# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Checkout51' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Checkout51

  target 'Checkout51Tests' do
    inherit! :search_paths
    pod 'Mockingjay'
  end

  target 'Checkout51UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
